### ISSUE TITLE
Does it support TAP feature?

### ISSUE THREAD

**Issue by ctiml** [makerdiary/python-keyboard#1]
Hi,
Using python code as keymap is quite simple, and I wonder if it support tap feature, like QMK [Mod-Tap](https://beta.docs.qmk.fm/using-qmk/advanced-keycodes/mod_tap)

Thanks for making this amazing keyboard!

**Comment by xiongyihui** [comment]
Will add it soon. Mod-Tap is similar to Tap-key which is already supported.

**Comment by ctiml** [comment]
Thanks for replying
