### ISSUE TITLE
Non-functional D and . Keys

### ISSUE THREAD

**Issue by benmontour** [makerdiary/python-keyboard#21]
I got my M60 fully assembled but I'm having issues with a couple of the keys. Everything seems to work fine right now except for the <kbd>D</kbd> and <kbd>.</kbd> keys. I've checked and as far as I can tell the switch is seated correctly. I'm not sure if I'm looking at a hardware issue with those two keys or something else. Any ideas?

**Comment by CVYY39** [comment]
I'd swap the keyswitch for another and see what happens. Are the keys not working at all? 

There is also a software issue with the default firmware and the d key, but I don't think it affects the . key: 

https://github.com/makerdiary/python-keyboard/issues/11

**Comment by xiongyihui** [comment]
How did you test these keys?
By default, <kbd>D</kbd>, <kbd>;</kbd> and <kbd>B</kbd> are used as tap-keys. Tapping these keys outputs normal keys. Holding down these keys activates additional functions.

**Comment by benmontour** [comment]
Neither tapping, nor holding produced any input from these keys. Holding and pressing the additional function keys that should work for <kbd>D</kbd> did not produce any results either.

**Comment by xiongyihui** [comment]
It is likely to be a hardware issue.
To double-check, We can test these keys with https://keyboard.makerdiary.com/#/test
![image](https://user-images.githubusercontent.com/948283/96526639-cabf2280-12b0-11eb-840a-08c7ade206f9.png)

You said <kbd>N</kbd> and  <kbd>.</kbd> didn't work on twitter. Now <kbd>N</kbd> and  <kbd>.</kbd> don't work. Is it related?

**Comment by ben-uptycs** [comment]
This was a hardware issue on my end. This can be closed. Sorry for the false issue.

**Comment by benmontour** [comment]
This was a hardware issue on my end. Closing this. Sorry for false issue.
