### ISSUE TITLE
TAP Key Delay

### ISSUE THREAD

**Issue by mehalter** [makerdiary/python-keyboard#6]
What is the current tap key delay? Would it be possible to add a feature to adjust this time?

**Comment by xiongyihui** [comment]
The max delay is 500 milliseconds. However, the tap key will be activated quicker when another key is pressed afterwards.
The implementation is at https://github.com/makerdiary/python-keyboard/blob/ed762e7ffd25137e41697f5afbda35af017b9577/keyboard/__init__.py#L85-L102

It is a good idea to add an option to adjust the time. Maybe move `is_tapped` into `Keyboard` class and use a property as the delay.

**Comment by mehalter** [comment]
Yeah I can give this a shot an open a PR! Would love to contribute. Is there documentation on setting up a development environment to test it the code on the board?

**Comment by xiongyihui** [comment]
Setting up a dev environment is easy:

1. copy `keyboard` directory of this repo to `lib` folder of the CIRCUITPY USB drive.
2. replace `from PYKB import *` with `from keyboard import *` in the `code.py` of the USB drive.

`PYKB` is a frozen version of `keyboard` and is compiled into the CircuitPython firmware. `adafruit_ble` is also compiled into the firmware.

**Comment by mehalter** [comment]
This has been addressed with #7 along with being able to adjust pair key delay as well
